#!/usr/bin/env bash
# Generate a trace-check module for a TLA+ model.
#
# Reads the model's VARIABLES declaration and emits <ModelDir>/<Model>Trace.tla
# (plus its .cfg) that checks a recorded behavior (a JSON file named by the
# TRACE_PATH env var) is a legal behavior of the model. The model stays the
# single source of truth: every variable is derived from its VARIABLES block, so
# there is nothing to hand-sync. Each variable pins uniformly (v = Trace[i].v)
# because we emit full snapshots and derive Items per trace from cover's domain.
#
# Usage: tools/tla/gen-trace-spec.sh <Model.tla>
# Then:  TRACE_PATH="/abs/path/behavior.ndjson" tools/tla/tlc <Model>Trace.tla
set -euo pipefail

[ $# -eq 1 ] || { echo "usage: $0 <Model.tla>" >&2; exit 1; }
model_path="$1"
[ -f "$model_path" ] || { echo "model not found: $model_path" >&2; exit 1; }

model_dir="$(cd "$(dirname "$model_path")" && pwd)"
model_file="$(basename "$model_path")"
model_name="${model_file%.tla}"
trace_name="${model_name}Trace"
trace_tla="$model_dir/$trace_name.tla"
trace_cfg="$model_dir/$trace_name.cfg"

# Extract variable names from the model's VARIABLES/VARIABLE block. The block
# runs from the VARIABLE(S) keyword up to the first line that is not part of the
# comma-separated list (a blank line or the next definition). We strip inline
# \* comments and commas, then collect the bare identifiers.
variables=$(awk '
    # Start capturing at a VARIABLE or VARIABLES keyword line.
    /^[[:space:]]*VARIABLES?([[:space:]]|$)/ { capture = 1 }
    capture {
        line = $0
        sub(/\\\*.*/, "", line)                 # drop inline \* comments
        sub(/^[[:space:]]*VARIABLES?/, "", line) # drop the keyword itself
        gsub(/,/, " ", line)                     # commas become separators
        n = split(line, toks, /[[:space:]]+/)
        emitted_on_line = 0
        for (i = 1; i <= n; i++) {
            if (toks[i] ~ /^[A-Za-z_][A-Za-z0-9_]*$/) {
                print toks[i]
                emitted_on_line++
            }
        }
        # Stop once we hit a line that is a defining line (contains ==) or, after
        # having captured at least one name, a line that produced no identifiers
        # (blank line ends the declaration list).
        if (line ~ /==/) { exit }
        if (captured_any && emitted_on_line == 0) { exit }
        if (emitted_on_line > 0) { captured_any = 1 }
    }
' "$model_path")

[ -n "$variables" ] || { echo "no VARIABLES found in $model_path" >&2; exit 1; }

# Build the per-variable pin lines for TraceInit and TraceNext.
init_pins=""
next_pins=""
for v in $variables; do
    init_pins+="    /\\ $v = Trace[1].$v"$'\n'
    next_pins+="       /\\ $v' = Trace[l+1].$v"$'\n'
done

{
    echo "---- MODULE $trace_name ----"
    echo "\\* GENERATED by tools/tla/gen-trace-spec.sh from $model_file -- do not edit."
    echo "\\* Checks that the behavior in \$TRACE_PATH is a legal behavior of $model_name."
    echo "EXTENDS $model_name, Sequences, Naturals, Json, IOUtils, TLC"
    echo ""
    echo "\\* First (only) behavior in the ND-JSON file: a sequence of state records."
    echo "Trace == ndJsonDeserialize(IOEnv.TRACE_PATH)[1]"
    echo ""
    echo "\\* Items derives from the recorded per-item coverage: the model stays the"
    echo "\\* single source of truth, the trace supplies the concrete item set."
    echo "TraceItems == DOMAIN Trace[1].cover"
    echo ""
    echo "VARIABLE l"
    echo ""
    echo "TraceInit =="
    echo "    /\\ l = 1"
    printf '%s' "$init_pins"
    echo ""
    echo "TraceNext =="
    echo "    \\/ /\\ l < Len(Trace)"
    echo "       /\\ l' = l + 1"
    printf '%s' "$next_pins"
    echo "       /\\ Next"
    echo "    \\/ /\\ l = Len(Trace)"
    echo "       /\\ UNCHANGED << vars, l >>"
    echo ""
    echo "TraceSpec == TraceInit /\\ [][TraceNext]_<< vars, l >> /\\ WF_<< vars, l >>(TraceNext)"
    echo ""
    echo "\\* Holds only if the whole trace was consumed step by step under Next."
    echo "Reached == l = Len(Trace)"
    echo ""
    echo "\\* A conforming trace advances (WF forces progress) until l = Len; a"
    echo "\\* non-conforming trace gets stuck before Len (Next false, no stutter"
    echo "\\* allowed yet), so this temporal property is violated and TLC reports it."
    echo "TraceConforms == <>Reached"
    echo "===="
} > "$trace_tla"

{
    echo "\\* GENERATED by tools/tla/gen-trace-spec.sh -- do not edit."
    echo "CONSTANTS Items <- TraceItems"
    echo "CONSTANT PollingEnabled = TRUE"
    echo "SPECIFICATION TraceSpec"
    echo "PROPERTY TraceConforms"
    echo "\\* A stuck (non-conforming) trace is a deadlock; suppress the deadlock"
    echo "\\* error so TLC proceeds to report the <>Reached temporal-property"
    echo "\\* violation, which is the intended non-conformance signal."
    echo "CHECK_DEADLOCK FALSE"
} > "$trace_cfg"

echo "$trace_tla"
