<Project Sdk="Microsoft.NET.Sdk.Razor">

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
        <ProjectReference Include="..\HomeBlaze.Storage\HomeBlaze.Storage.csproj" />
        <ProjectReference Include="..\HomeBlaze.Components\HomeBlaze.Components.csproj" />
        <ProjectReference Include="..\HomeBlaze.Abstractions\HomeBlaze.Abstractions.csproj" />
        <ProjectReference Include="..\HomeBlaze.Components.Abstractions\HomeBlaze.Components.Abstractions.csproj" />
        <ProjectReference Include="..\HomeBlaze.Services\HomeBlaze.Services.csproj" />
        <PackageReference Include="MudBlazor" />
        <PackageReference Include="BlazorMonaco" />
        <PackageReference Include="Markdig" />
    </ItemGroup>

</Project>
