<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<GenerateProgramFile>false</GenerateProgramFile>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	</PropertyGroup>

	<ItemGroup>
		<DotNetCliToolReference Include="dotnet-xunit" Version="2.3.1" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="BenchmarkDotNet" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="Microsoft.VisualStudio.DiagnosticsHub.BenchmarkDotNetDiagnosers" />
		<PackageReference Include="NBench" />
		<PackageReference Include="Pro.NBench.xUnit" />
		<PackageReference Include="xunit" />
		<PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup>
      <ProjectReference Include="..\Namotion.Interceptor.Dynamic\Namotion.Interceptor.Dynamic.csproj" />
      <ProjectReference Include="..\Namotion.Interceptor.Generator\Namotion.Interceptor.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
      <ProjectReference Include="..\Namotion.Interceptor.Registry\Namotion.Interceptor.Registry.csproj" />
      <ProjectReference Include="..\Namotion.Interceptor.Connectors\Namotion.Interceptor.Connectors.csproj" />
	  <ProjectReference Include="..\Namotion.Interceptor.Validation\Namotion.Interceptor.Validation.csproj" />
	</ItemGroup>
</Project>
