<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<PackageReference Include="FluentModbus" />
		<PackageReference Include="SonarAnalyzer.CSharp" PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="Namotion.Interceptor.Modbus.Tests" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Namotion.Interceptor.Connectors\Namotion.Interceptor.Connectors.csproj" />
	</ItemGroup>
</Project>
