<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <InternalsVisibleTo Include="Namotion.Interceptor.Tracking.Tests" />
        <InternalsVisibleTo Include="Namotion.Interceptor.Connectors.Tests" />
        <InternalsVisibleTo Include="Namotion.Interceptor.WebSocket.Tests" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="SonarAnalyzer.CSharp">
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="System.Reactive" />
        <ProjectReference Include="..\Namotion.Interceptor\Namotion.Interceptor.csproj" />
    </ItemGroup>

</Project>
