<Project Sdk="Microsoft.NET.Sdk.Razor">

    <ItemGroup>
        <ProjectReference Include="..\HomeBlaze.OpcUa\HomeBlaze.OpcUa.csproj" />
        <ProjectReference Include="..\HomeBlaze.Components.Abstractions\HomeBlaze.Components.Abstractions.csproj" />
        <ProjectReference Include="..\HomeBlaze.Components\HomeBlaze.Components.csproj" />
        <PackageReference Include="MudBlazor" />
    </ItemGroup>

</Project>
