<Project Sdk="Microsoft.NET.Sdk.Razor">

    <ItemGroup>
        <ProjectReference Include="..\HomeBlaze.History.InMemory\HomeBlaze.History.InMemory.csproj" />
        <ProjectReference Include="..\HomeBlaze.Components.Abstractions\HomeBlaze.Components.Abstractions.csproj" />
        <PackageReference Include="MudBlazor" />
    </ItemGroup>

</Project>
