<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="SonarAnalyzer.CSharp" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Namotion.Interceptor.Tests" />
        <InternalsVisibleTo Include="Namotion.Interceptor.Benchmark" />
        <InternalsVisibleTo Include="Namotion.Interceptor.Tracking" />
        <InternalsVisibleTo Include="Namotion.Interceptor.Connectors.Tests" />
    </ItemGroup>

</Project>
