<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\src\Namotion.Interceptor.Generator\Namotion.Interceptor.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\..\..\..\..\src\Namotion.Interceptor.WebSocket\Namotion.Interceptor.WebSocket.csproj" />
    <ProjectReference Include="..\..\..\..\domain\Coffee\Coffee.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Shared\*.cs" LinkBase="Shared" />
  </ItemGroup>

</Project>
