using System.Collections.Generic;
using System.Linq;
using System.Text;
using Namotion.Interceptor.Generator.Models;

namespace Namotion.Interceptor.Generator;

internal static class SubjectCodeGenerator
{
    /// <summary>
    /// Generates the C# code for an interceptor subject class.
    /// </summary>
    public static string Generate(SubjectMetadata metadata, bool isJsonIgnoreAvailable = true)
    {
        var builder = new StringBuilder();

        EmitFileHeader(builder, isJsonIgnoreAvailable);
        EmitNamespaceOpening(builder, metadata.NamespaceName);
        EmitContainingTypeOpening(builder, metadata.ContainingTypes);
        EmitClassDeclaration(builder, metadata);
        EmitNotifyPropertyChangedImplementation(builder, metadata);
        EmitInterceptorSubjectImplementation(builder, metadata, isJsonIgnoreAvailable);
        EmitDefaultProperties(builder, metadata);
        EmitConstructors(builder, metadata);
        EmitProperties(builder, metadata);
        EmitMethods(builder, metadata);
        EmitHelperMethods(builder, metadata);
        EmitClassClosing(builder);
        EmitContainingTypeClosing(builder, metadata.ContainingTypes);
        EmitNamespaceClosing(builder, metadata.NamespaceName);

        return builder.ToString();
    }

    /// <summary>
    /// Returns private for sealed subjects and protected for inheritable subjects.
    /// </summary>
    private static string ProtectedUnlessSealed(SubjectMetadata metadata) => metadata.IsSealed ? "private" : "protected";

    /// <summary>
    /// Returns the hiding modifier for a generated member named by <see cref="MemberNames"/>.
    /// </summary>
    private static string HidingModifier(SubjectMetadata metadata, string memberName)
        => metadata.BaseClass.HiddenMemberNames.Contains(memberName) ? "new " : "";

    /// <summary>
    /// Generates the filename for the generated code.
    /// </summary>
    public static string GetFileName(SubjectMetadata metadata)
    {
        // Symbol names normalize source escapes and trivia that AddSource rejects in hint names.
        return metadata.FullTypeName
            .Replace("global::", "")
            .Replace("@", "") + ".g.cs";
    }

    private static void EmitFileHeader(StringBuilder builder, bool isJsonIgnoreAvailable)
    {
        builder.Append("""
            // <auto-generated>
            //     This code was generated by Namotion.Interceptor.Generator
            // </auto-generated>

            using Namotion.Interceptor;
            using Namotion.Interceptor.Interceptors;

            using System;
            using System.Collections.Concurrent;
            using System.Collections.Generic;
            using System.Collections.Frozen;
            using System.ComponentModel;
            using System.Linq;
            using System.Reflection;
            using System.Runtime.CompilerServices;

            """);

        EmitJsonIgnoreUsing(builder, isJsonIgnoreAvailable);

        builder.Append("""

            #pragma warning disable CS8669
            #pragma warning disable CS0649
            #pragma warning disable CS0067
            #pragma warning disable CS9193


            """);
    }

    /// <summary>
    /// Emits the JsonIgnore using directive when the consuming compilation can resolve the attribute.
    /// </summary>
    private static void EmitJsonIgnoreUsing(StringBuilder builder, bool isJsonIgnoreAvailable)
    {
        if (isJsonIgnoreAvailable)
        {
            builder.AppendLine("using System.Text.Json.Serialization;");
        }
    }

    private static void EmitJsonIgnore(StringBuilder builder, bool isJsonIgnoreAvailable)
    {
        if (isJsonIgnoreAvailable)
        {
            builder.AppendLine("        [JsonIgnore]");
        }
    }

    private static void EmitNamespaceOpening(StringBuilder builder, string? namespaceName)
    {
        if (namespaceName is null)
        {
            return;
        }

        builder.AppendLine($"namespace {namespaceName}");
        builder.AppendLine("{");
    }

    private static void EmitNamespaceClosing(StringBuilder builder, string? namespaceName)
    {
        if (namespaceName is null)
        {
            return;
        }

        builder.AppendLine("}");
    }

    private static void EmitContainingTypeOpening(StringBuilder builder, ContainingType[] containingTypes)
    {
        foreach (var containingType in containingTypes)
        {
            builder.AppendLine($"    partial {containingType.Keyword} {containingType.Name}");
            builder.AppendLine("    {");
        }
    }

    private static void EmitContainingTypeClosing(StringBuilder builder, ContainingType[] containingTypes)
    {
        foreach (var _ in containingTypes)
        {
            builder.AppendLine("    }");
        }
    }

    private static void EmitClassDeclaration(StringBuilder builder, SubjectMetadata metadata)
    {
        var interfaces = metadata.BaseClass.HasInpc
            ? "IInterceptorSubject"
            : "IInterceptorSubject, INotifyPropertyChanged, IRaisePropertyChanged";

        builder.AppendLine($"    {metadata.AccessModifier} partial class {metadata.ClassName} : {interfaces}");
        builder.AppendLine("    {");
    }

    private static void EmitClassClosing(StringBuilder builder)
    {
        builder.AppendLine("    }");
    }

    private static void EmitNotifyPropertyChangedImplementation(StringBuilder builder, SubjectMetadata metadata)
    {
        if (metadata.BaseClass.HasInpc)
        {
            return;
        }

        builder.AppendLine($"        {HidingModifier(metadata, MemberNames.PropertyChanged)}public event PropertyChangedEventHandler? PropertyChanged;");
        builder.AppendLine();
        builder.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        builder.AppendLine($"        {HidingModifier(metadata, MemberNames.RaisePropertyChanged)}{ProtectedUnlessSealed(metadata)} void RaisePropertyChanged(string propertyName) => PropertyChanged?.Invoke(this, PropertyChangedEventArgsCache.Get(propertyName));");
        builder.AppendLine();
        builder.AppendLine("        void IRaisePropertyChanged.RaisePropertyChanged(string propertyName) => RaisePropertyChanged(propertyName);");
        builder.AppendLine();
    }

    private static void EmitInterceptorSubjectImplementation(StringBuilder builder, SubjectMetadata metadata, bool isJsonIgnoreAvailable)
    {
        // Re-emit Properties in derived subjects so the static DefaultProperties binds to their own type.
        if (!metadata.BaseClass.EmitsInterceptionMembers)
        {
            EmitJsonIgnore(builder, isJsonIgnoreAvailable);
            builder.AppendLine("        IReadOnlyDictionary<string, SubjectPropertyMetadata> IInterceptorSubject.Properties => GetInstanceProperties() ?? DefaultProperties;");
            builder.AppendLine();
            return;
        }

        builder.AppendLine("        private IInterceptorExecutor? _context;");
        builder.AppendLine("        private IReadOnlyDictionary<string, SubjectPropertyMetadata>? _properties;");
        builder.AppendLine();
        EmitJsonIgnore(builder, isJsonIgnoreAvailable);
        builder.AppendLine("        IInterceptorSubjectContext IInterceptorSubject.Context => InterceptorExecutor.GetOrCreate(ref _context, this);");
        builder.AppendLine();
        EmitJsonIgnore(builder, isJsonIgnoreAvailable);
        builder.AppendLine("        ConcurrentDictionary<(string? property, string key), object?> IInterceptorSubject.Data { get; } = new();");
        builder.AppendLine();
        EmitJsonIgnore(builder, isJsonIgnoreAvailable);
        builder.AppendLine("        IReadOnlyDictionary<string, SubjectPropertyMetadata> IInterceptorSubject.Properties => GetInstanceProperties() ?? DefaultProperties;");
        builder.AppendLine();
        EmitJsonIgnore(builder, isJsonIgnoreAvailable);
        builder.AppendLine("        object IInterceptorSubject.SyncRoot { get; } = new object();");
        builder.AppendLine();
        builder.AppendLine("        void IInterceptorSubject.AddProperties(params IEnumerable<SubjectPropertyMetadata> properties)");
        builder.AppendLine("        {");
        builder.AppendLine("            lock (((IInterceptorSubject)this).SyncRoot)");
        builder.AppendLine("            {");
        // Interface dispatch starts the merge from the most-derived property set.
        builder.AppendLine("                _properties = ((IInterceptorSubject)this).Properties");
        builder.AppendLine("                    .Concat(properties.Select(p => new KeyValuePair<string, SubjectPropertyMetadata>(p.Name, p)))");
        builder.AppendLine("                    .ToFrozenDictionary();");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
    }

    /// <summary>
    /// Emits properties with precedence: own declarations, inherited properties, then adopted interface defaults.
    /// </summary>
    private static void EmitDefaultProperties(StringBuilder builder, SubjectMetadata metadata)
    {
        var newModifier = metadata.BaseClass.TypeName is not null ? "new " : "";

        builder.AppendLine($"        public {newModifier}static IReadOnlyDictionary<string, SubjectPropertyMetadata> DefaultProperties {{ get; }} =");

        if (metadata.BaseClass.TypeName is null)
        {
            EmitPropertyDictionary(builder, metadata, metadata.Properties);
            builder.AppendLine("            .ToFrozenDictionary();");
            builder.AppendLine();
            return;
        }

        // Class-declared explicit implementations belong to the own-declaration tier, despite their interface casts.
        EmitPropertyDictionary(builder, metadata, metadata.Properties.Where(property => !property.IsFromInterface));
        builder.AppendLine($"            .Concat({metadata.BaseClass.TypeName}.DefaultProperties)");

        if (metadata.Properties.Any(property => property.IsFromInterface))
        {
            builder.AppendLine("            .Concat(");
            EmitPropertyDictionary(builder, metadata, metadata.Properties.Where(property => property.IsFromInterface), extraIndent: "    ");
            builder.AppendLine("            )");
        }

        // Keep the first key to preserve precedence. GroupBy supports netstandard2.0 consumers; DistinctBy does not.
        builder.AppendLine("            .GroupBy(pair => pair.Key)");
        builder.AppendLine("            .Select(group => group.First())");
        builder.AppendLine("            .ToFrozenDictionary();");
        builder.AppendLine();
    }

    private static void EmitPropertyDictionary(
        StringBuilder builder,
        SubjectMetadata metadata,
        IEnumerable<PropertyMetadata> properties,
        string extraIndent = "")
    {
        builder.AppendLine($"{extraIndent}            new Dictionary<string, SubjectPropertyMetadata>");
        builder.AppendLine($"{extraIndent}            {{");

        // Indexer assignments avoid type-initialization failures for duplicate keys within a tier.
        // Extraction already deduplicates these; cross-tier precedence is resolved separately.
        foreach (var property in properties)
        {
            EmitPropertyDictionaryEntry(builder, metadata, property, extraIndent);
        }

        builder.AppendLine($"{extraIndent}            }}");
    }

    private static void EmitPropertyDictionaryEntry(
        StringBuilder builder, SubjectMetadata metadata, PropertyMetadata property, string extraIndent)
    {
        // Explicit implementations require an interface cast, just like adopted defaults.
        var accessorInterfaceTypeName = property.IsFromInterface
            ? property.InterfaceTypeName
            : property.ExplicitInterfaceTypeName;

        var castTypeName = accessorInterfaceTypeName ?? metadata.ClassName;

        var nameofArgument = accessorInterfaceTypeName is not null
            ? $"{accessorInterfaceTypeName}.{property.Name}"
            : property.Name;

        // Class entries are declared on this subject. DeclaredOnly avoids ambiguous lookup when 'new' changes a property's type.
        var declaredOnlyFlag = accessorInterfaceTypeName is not null ? "" : " | BindingFlags.DeclaredOnly";

        // Interface access bypasses the executor, including class-declared explicit implementations.
        var isIntercepted = accessorInterfaceTypeName is null && property.IsPartial;

        var getterLambda = GetGetterLambda(property, castTypeName);
        var setterLambda = GetSetterLambda(property, castTypeName);

        builder.AppendLine($"{extraIndent}                    [\"{property.Name}\"] = new SubjectPropertyMetadata(");
        builder.AppendLine($"{extraIndent}                        typeof({castTypeName}).GetProperty(nameof({nameofArgument}), BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance{declaredOnlyFlag})!,");
        builder.AppendLine($"{extraIndent}                        {getterLambda},");
        builder.AppendLine($"{extraIndent}                        {setterLambda},");
        builder.AppendLine($"{extraIndent}                        isIntercepted: {(isIntercepted ? "true" : "false")},");
        builder.AppendLine(isIntercepted
            ? $"{extraIndent}                        isDynamic: false).WithStoredValueReader<{property.FullTypeName}>(static (o) => (({metadata.ClassName})o)._{property.Name}),"
            : $"{extraIndent}                        isDynamic: false),");
    }

    private static string GetGetterLambda(PropertyMetadata property, string castTypeName)
    {
        return property.HasGetter || property.HasInheritedGetter
            ? $"(o) => (({castTypeName})o).{property.Name}"
            : "null";
    }

    private static string GetSetterLambda(PropertyMetadata property, string castTypeName)
    {
        // Init-only accessors cannot be called by a setter lambda after construction.
        return property.HasSetter || property.HasInheritedSetter
            ? $"(o, v) => (({castTypeName})o).{property.Name} = ({property.FullTypeName})v"
            : "null";
    }

    /// <summary>
    /// Emits SetsRequiredMembers when required by the constructor chain.
    /// </summary>
    private static void EmitSetsRequiredMembersAttribute(StringBuilder builder, SubjectMetadata metadata)
    {
        if (metadata.ParameterlessConstructorSetsRequiredMembers)
        {
            // Qualification also resolves consumer polyfills when the subject namespace shadows System.
            builder.AppendLine("        [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]");
        }
    }

    private static void EmitConstructors(StringBuilder builder, SubjectMetadata metadata)
    {
        if (metadata.NeedsGeneratedParameterlessConstructor)
        {
            EmitSetsRequiredMembersAttribute(builder, metadata);
            builder.AppendLine($"        public {metadata.ClassName}()");
            builder.AppendLine("        {");
            builder.AppendLine("        }");
            builder.AppendLine();
        }

        if (metadata.HasOrWillHaveParameterlessConstructor)
        {
            EmitSetsRequiredMembersAttribute(builder, metadata);
            builder.AppendLine($"        public {metadata.ClassName}(IInterceptorSubjectContext context) : this()");
            builder.AppendLine("        {");
            builder.AppendLine("            ((IInterceptorSubject)this).Context.AddFallbackContext(context);");
            builder.AppendLine("        }");
            builder.AppendLine();
        }
    }

    private static void EmitProperties(StringBuilder builder, SubjectMetadata metadata)
    {
        foreach (var property in metadata.Properties.Where(p => p.IsPartial))
        {
            EmitProperty(builder, property, metadata);
        }
    }

    private static void EmitProperty(StringBuilder builder, PropertyMetadata property, SubjectMetadata metadata)
    {
        builder.AppendLine($"        private {property.FullTypeName} _{property.Name};");
        builder.AppendLine();

        var additionalModifiers = GetAdditionalPropertyModifiers(property);
        var requiredModifier = property.IsRequired ? "required " : "";

        builder.AppendLine($"        {property.AccessModifier} {requiredModifier}{additionalModifiers}partial {property.FullTypeName} {property.Name}");
        builder.AppendLine("        {");

        EmitPropertyGetter(builder, property, metadata);
        EmitPropertySetter(builder, property, metadata);

        builder.AppendLine("        }");
        builder.AppendLine();

        if (property.HasSetter || property.HasInit)
        {
            builder.AppendLine($"        partial void On{property.Name}Changing(ref {property.FullTypeName} newValue, ref bool cancel);");
            builder.AppendLine();
            builder.AppendLine($"        partial void On{property.Name}Changed({property.FullTypeName} newValue);");
            builder.AppendLine();
        }
    }

    private static string GetAdditionalPropertyModifiers(PropertyMetadata property)
    {
        // Partial declarations must agree on modifiers (CS8800); retaining 'new' also prevents CS0108.
        var additionalModifiers = "";
        if (property.IsNew)
        {
            additionalModifiers += "new ";
        }

        if (property.IsVirtual)
        {
            additionalModifiers += "virtual ";
        }

        if (property.IsSealed)
        {
            additionalModifiers += "sealed ";
        }

        if (property.IsOverride)
        {
            additionalModifiers += "override ";
        }

        return additionalModifiers;
    }

    private static void EmitPropertyGetter(StringBuilder builder, PropertyMetadata property, SubjectMetadata metadata)
    {
        if (property.HasGetter)
        {
            var getterModifiers = property.GetterAccessModifier is not null ? $"{property.GetterAccessModifier} " : "";
            builder.AppendLine($"            {getterModifiers}get");
            builder.AppendLine("            {");
            builder.AppendLine($"                return GetPropertyValue<{property.FullTypeName}>(nameof({property.Name}), static (o) => (({metadata.ClassName})o)._{property.Name});");
            builder.AppendLine("            }");
        }
    }

    private static void EmitPropertySetter(StringBuilder builder, PropertyMetadata property, SubjectMetadata metadata)
    {
        if (property.HasSetter || property.HasInit)
        {
            var accessorText = property.HasInit ? "init" : "set";
            var setterModifiers = property.SetterAccessModifier is not null ? $"{property.SetterAccessModifier} " : "";

            var raisePropertyChangedCall = GetRaisePropertyChangedCall(property, metadata);

            builder.AppendLine($"            {setterModifiers}{accessorText}");
            builder.AppendLine("            {");
            builder.AppendLine("                var newValue = value;");
            builder.AppendLine("                var cancel = false;");
            builder.AppendLine($"                On{property.Name}Changing(ref newValue, ref cancel);");
            builder.AppendLine($"                if (!cancel && SetPropertyValue(nameof({property.Name}), newValue, _{property.Name}, static (o, v) => (({metadata.ClassName})o)._{property.Name} = v))");
            builder.AppendLine("                {");
            builder.AppendLine($"                    On{property.Name}Changed(_{property.Name});");
            builder.AppendLine($"                    {raisePropertyChangedCall};");
            builder.AppendLine("                }");
            builder.AppendLine("            }");
        }
    }

    private static string GetRaisePropertyChangedCall(PropertyMetadata property, SubjectMetadata metadata)
    {
        // The subject attribute alone does not guarantee a callable inherited helper.
        if (metadata.BaseClass.HasInterceptorSubject && metadata.BaseClass.HasCallableRaisePropertyChanged)
        {
            return $"RaisePropertyChanged(nameof({property.Name}))";
        }

        if (metadata.BaseClass.HasInpc)
        {
            return $"((IRaisePropertyChanged)this).RaisePropertyChanged(nameof({property.Name}))";
        }

        return $"RaisePropertyChanged(nameof({property.Name}))";
    }

    private static void EmitMethods(StringBuilder builder, SubjectMetadata metadata)
    {
        foreach (var method in metadata.Methods)
        {
            EmitMethod(builder, method, metadata);
        }
    }

    private static void EmitMethod(StringBuilder builder, MethodMetadata method, SubjectMetadata metadata)
    {
        var parameterDeclarations = string.Join(", ", method.Parameters.Select(p => $"{p.Type} {p.Name}"));
        var directParameterCode = string.Join(", ", method.Parameters.Select((p, i) => $"({p.Type})p[{i}]!"));
        var invokeParameterCode = method.Parameters.Any()
            ? ", " + string.Join(", ", method.Parameters.Select(p => p.Name))
            : "";

        if (method.ReturnType != "void")
        {
            builder.AppendLine($"        public {method.ReturnType} {method.Name}({parameterDeclarations})");
            builder.AppendLine("        {");
            builder.AppendLine($"            return ({method.ReturnType})InvokeMethod(\"{method.Name}\", static (s, p) => (({metadata.ClassName})s).{method.FullMethodName}({directParameterCode}){invokeParameterCode})!;");
            builder.AppendLine("        }");
        }
        else
        {
            builder.AppendLine($"        public {method.ReturnType} {method.Name}({parameterDeclarations})");
            builder.AppendLine("        {");
            builder.AppendLine($"            InvokeMethod(\"{method.Name}\", static (s, p) => {{ (({metadata.ClassName})s).{method.FullMethodName}({directParameterCode}); return null; }}{invokeParameterCode});");
            builder.AppendLine("        }");
        }

        builder.AppendLine();
    }

    private static void EmitHelperMethods(StringBuilder builder, SubjectMetadata metadata)
    {
        if (!metadata.BaseClass.EmitsInterceptionMembers)
        {
            return;
        }

        var modifier = ProtectedUnlessSealed(metadata);

        // DynamicSubjectFactory discovers inherited protected properties; a property here would
        // become an unintended intercepted property on generated subjects proxied by Castle.
        builder.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        builder.AppendLine($"        {HidingModifier(metadata, MemberNames.GetInstanceProperties)}{modifier} IReadOnlyDictionary<string, SubjectPropertyMetadata>? GetInstanceProperties() => _properties;");
        builder.AppendLine();
        builder.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        builder.AppendLine($"        {HidingModifier(metadata, MemberNames.GetPropertyValue)}{modifier} TProperty GetPropertyValue<TProperty>(string propertyName, Func<IInterceptorSubject, TProperty> readValue)");
        builder.AppendLine("        {");
        builder.AppendLine("            return _context is not null ? _context.GetPropertyValue(propertyName, readValue)! : readValue(this)!;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        builder.AppendLine($"        {HidingModifier(metadata, MemberNames.SetPropertyValue)}{modifier} bool SetPropertyValue<TProperty>(string propertyName, TProperty newValue, TProperty currentValue, Action<IInterceptorSubject, TProperty> setValue)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (_context is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                setValue(this, newValue);");
        builder.AppendLine("                return true;");
        builder.AppendLine("            }");
        builder.AppendLine("            else");
        builder.AppendLine("            {");
        builder.AppendLine("                return _context.SetPropertyValue(propertyName, newValue, currentValue, setValue);");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        builder.AppendLine($"        {HidingModifier(metadata, MemberNames.InvokeMethod)}{modifier} object? InvokeMethod(string methodName, Func<IInterceptorSubject, object?[], object?> invokeMethod, params object?[] parameters)");
        builder.AppendLine("        {");
        builder.AppendLine("            return _context is not null ? _context.InvokeMethod(methodName, parameters, invokeMethod) : invokeMethod(this, parameters);");
        builder.AppendLine("        }");
    }
}
