using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using HomeBlaze.Abstractions.Attributes;
using Namotion.Devices.SunSpec.Definitions;
using Namotion.Interceptor.Modbus;

namespace Namotion.Devices.SunSpec.Generator;

/// <summary>
/// Writes the C# of a generated model file and of the model factory.
/// </summary>
internal static class SunSpecClassWriter
{
    private const string FileHeader =
        "// <auto-generated>\n" +
        "//     Generated by Namotion.Devices.SunSpec.Generator from the SunSpec model definitions. Do not edit.\n" +
        "// </auto-generated>\n" +
        "#nullable enable\n";

    private static readonly string[] Imports =
    [
        "HomeBlaze.Abstractions", "HomeBlaze.Abstractions.Attributes", "Namotion.Devices.SunSpec.Definitions", "Namotion.Interceptor",
        "Namotion.Interceptor.Attributes", "Namotion.Interceptor.Modbus", "Namotion.Interceptor.Modbus.Attributes"
    ];

    private sealed record PointPlan(string Name, string TypeName, string Documentation, string RegisterAttribute, string? StateAttribute);

    private sealed record GroupPropertyPlan(string PropertyName, string GroupName, string ClassName, bool IsSingle, string Documentation);

    private sealed record AncestorInfo(string ClassName, SunSpecGroupDefinition Group);

    // Ancestors start with the direct parent, which the generated code reaches as Parent, then Parent.Parent and so on.
    private sealed record GroupPlan(SunSpecGroupDefinition Definition, string ClassName, string ParentClassName, IReadOnlyList<AncestorInfo> Ancestors, string ModelsText);

    private sealed record EnumPlan(string Name, SunSpecPointDefinition Point, SunSpecPointMap Map);

    // The model or group class being written. Points whose scale factor lives in an enclosing group are collected in
    // ProvidedScaleFactors with the expression reaching that scale factor.
    private sealed class OwnerScope(string prefix, IEnumerable<string> reservedMembers, IReadOnlyList<AncestorInfo> ancestors)
    {
        public string Prefix { get; } = prefix;

        public HashSet<string> Members { get; } = new(reservedMembers, StringComparer.Ordinal);

        public IReadOnlyList<AncestorInfo> Ancestors { get; } = ancestors;

        public List<(string Name, string Expression)> ProvidedScaleFactors { get; } = [];
    }

    // State of one generated file: names in use across files, and the enums and group classes queued for this file.
    private sealed class FileState(HashSet<string> typeNames)
    {
        public HashSet<string> TypeNames { get; } = typeNames;

        public List<EnumPlan> Enums { get; } = [];

        public List<GroupPlan> GroupClasses { get; } = [];
    }

    public static string WriteModelFile(SunSpecClassPlan plan, HashSet<string> typeNames)
    {
        var writer = new CodeWriter();
        writer.Raw(FileHeader);
        writer.Line();
        foreach (var import in Imports)
        {
            writer.Line($"using {import};");
        }

        writer.Line();
        writer.Line("namespace Namotion.Devices.SunSpec.Models;");

        var state = new FileState(typeNames);
        WriteModelClass(writer, plan, state);

        // Writing a group class may queue its nested group classes.
        for (var index = 0; index < state.GroupClasses.Count; index++)
        {
            WriteGroupClass(writer, state.GroupClasses[index], state);
        }

        foreach (var enumPlan in state.Enums)
        {
            WriteEnum(writer, enumPlan);
        }

        return writer.ToString();
    }

    public static string WriteFactoryFile(IReadOnlyList<SunSpecClassPlan> plans)
    {
        var writer = new CodeWriter();
        writer.Raw(FileHeader);
        writer.Line();
        writer.Line("namespace Namotion.Devices.SunSpec.Models;");
        writer.Line();
        writer.Summary("Creates the generated model subjects by SunSpec model ID.");
        writer.Line("internal static class SunSpecModelFactory");
        writer.Open();
        writer.Summary("Gets whether a generated class exists for <paramref name=\"modelId\"/>.");
        writer.Line("public static bool IsGenerated(int modelId) => modelId switch");
        writer.Open();
        foreach (var plan in plans)
        {
            writer.Line($"{string.Join(" or ", plan.ModelIds)} => true,");
        }

        writer.Line("_ => false");
        writer.Close(";");
        writer.Line();
        writer.Summary("Creates the generated model subject for <paramref name=\"modelId\"/>, or returns <c>null</c> when there is none.");
        writer.Line("public static ISunSpecModel? TryCreate(int modelId, int baseAddress, int length) => modelId switch");
        writer.Open();
        foreach (var plan in plans)
        {
            writer.Line(plan.IsFamily
                ? $"{string.Join(" or ", plan.ModelIds)} => new {plan.ClassName}(modelId, baseAddress, length),"
                : $"{plan.ModelIds[0]} => new {plan.ClassName}(baseAddress, length),");
        }

        writer.Line("_ => null");
        writer.Close(";");
        writer.Close();
        return writer.ToString();
    }

    private static void WriteModelClass(CodeWriter writer, SunSpecClassPlan plan, FileState state)
    {
        var top = plan.Definition.Group;
        var className = plan.ClassName;
        if (top.Points.Count < 2 || top.Points[0].Name != "ID" || top.Points[1].Name != "L")
        {
            throw new InvalidDataException($"Model {plan.Definition.Id} does not start with the ID and L points.");
        }

        AddTypeName(state.TypeNames, className);

        var modelsText = (plan.IsFamily ? "models " : "model ") + string.Join(", ", plan.ModelIds);
        var scope = new OwnerScope(className, SunSpecMemberNames.Model, []);
        var points = CollectPoints(top, isTopLevel: true, scope, state);
        var groups = CollectGroups(top, className, scope, [new AncestorInfo(className, top)], state, modelsText);

        writer.Line();
        writer.Summary(ModelSummary(plan));
        writer.Line("[InterceptorSubject]");
        writer.Line($"public partial class {className} : ISunSpecModel, ITitleProvider{(groups.Count > 0 ? ", ISunSpecGroupOwner" : "")}");
        writer.Open();
        writer.Summary("Initializes the model at <paramref name=\"baseAddress\"/>, the address of its ID register, with <paramref name=\"length\"/> registers after the ID and length registers.");
        writer.Line($"public {className}({(plan.IsFamily ? "int modelId, " : "")}int baseAddress, int length)");
        writer.Open();
        if (plan.IsFamily)
        {
            writer.Line("ModelId = modelId;");
        }

        writer.Line("BaseAddress = baseAddress;");
        writer.Line("Length = length;");
        writer.Line("ModelIdRegister = null;");
        WriteInitializers(writer, points, groups);
        writer.Close();
        writer.Line();
        writer.Line("/// <inheritdoc />");
        writer.Line(plan.IsFamily ? "public int ModelId { get; }" : $"public int ModelId => {plan.Definition.Id};");
        writer.Line();
        writer.Line("/// <inheritdoc />");
        writer.Line("public int BaseAddress { get; }");
        writer.Line();
        writer.Line("/// <inheritdoc />");
        writer.Line("public int Length { get; }");
        WriteModelTitle(writer, plan);
        writer.Line();
        writer.Line("/// <inheritdoc />");
        writer.Line("[ModbusRegister(0, ModbusDataType.U16, Access = ModbusAccess.ReadOnly)]");
        writer.Line("public partial ushort? ModelIdRegister { get; internal set; }");
        WritePoints(writer, points);
        WriteGroupProperties(writer, groups);
        WriteUpdateGroups(writer, groups);
        writer.Close();
    }

    // A family's description is specific to its representative, so only single models carry one.
    private static string ModelSummary(SunSpecClassPlan plan)
    {
        var top = plan.Definition.Group;
        if (!plan.IsFamily)
        {
            return $"SunSpec model {plan.Definition.Id}: {CSharpText.XmlText(Label(top))}.{Description(top)}";
        }

        var members = plan.Models.Select(model => $"{model.Id} ({CSharpText.XmlText(Label(model.Group))})");
        return $"SunSpec models {string.Join(", ", members)}.";
    }

    // A family returns the label of the model it was created for; the representative's label is the fallback.
    private static void WriteModelTitle(CodeWriter writer, SunSpecClassPlan plan)
    {
        var representativeTitle = CSharpText.Literal(Label(plan.Definition.Group));
        writer.Line();
        writer.Line("/// <inheritdoc />");
        if (!plan.IsFamily)
        {
            writer.Line($"public string Title => {representativeTitle};");
            return;
        }

        writer.Line("public string Title => ModelId switch");
        writer.Open();
        foreach (var model in plan.Models.Where(model => model.Id != plan.Definition.Id))
        {
            writer.Line($"{model.Id} => {CSharpText.Literal(Label(model.Group))},");
        }

        writer.Line($"_ => {representativeTitle}");
        writer.Close(";");
    }

    private static void WriteGroupClass(CodeWriter writer, GroupPlan plan, FileState state)
    {
        var group = plan.Definition;
        var scope = new OwnerScope(plan.ClassName[..^"Group".Length], SunSpecMemberNames.Group, plan.Ancestors);
        var points = CollectPoints(group, isTopLevel: false, scope, state);
        var childAncestors = plan.Ancestors.Prepend(new AncestorInfo(plan.ClassName, group)).ToArray();
        var groups = CollectGroups(group, plan.ClassName, scope, childAncestors, state, plan.ModelsText);

        var interfaces = new List<string> { "IModbusBaseAddressProvider", "ITitleProvider" };
        if (scope.ProvidedScaleFactors.Count > 0)
        {
            interfaces.Add("IModbusScaleFactorProvider");
        }

        if (groups.Count > 0)
        {
            interfaces.Add("ISunSpecGroupOwner");
        }

        writer.Line();
        writer.Summary($"{CSharpText.XmlText(Label(group))} group of SunSpec {plan.ModelsText}.{Description(group)}");
        writer.Line("[InterceptorSubject]");
        writer.Line($"public partial class {plan.ClassName} : {string.Join(", ", interfaces)}");
        writer.Open();
        writer.Summary("Initializes the instance <paramref name=\"index\"/> of this group in <paramref name=\"parent\"/> at <paramref name=\"baseAddress\"/>.");
        writer.Line($"public {plan.ClassName}({plan.ParentClassName} parent, int baseAddress, int index)");
        writer.Open();
        writer.Line("Parent = parent;");
        writer.Line("BaseAddress = baseAddress;");
        writer.Line("Index = index;");
        WriteInitializers(writer, points, groups);
        writer.Close();
        writer.Line();
        writer.Summary("Gets the model or group containing this group.");
        writer.Line($"public {plan.ParentClassName} Parent {{ get; }}");
        writer.Line();
        writer.Line("/// <inheritdoc />");
        writer.Line("public int BaseAddress { get; }");
        writer.Line();
        writer.Summary("Gets the zero-based position of this instance within its group.");
        writer.Line("public int Index { get; }");
        writer.Line();
        writer.Line("/// <inheritdoc />");
        writer.Line(group.Count.IsSingle
            ? $"public string Title => {CSharpText.Literal(Label(group))};"
            : $"public string Title => $\"{CSharpText.InterpolationText(Label(group))} {{Index + 1}}\";");
        WritePoints(writer, points);
        WriteGroupProperties(writer, groups);
        WriteScaleFactorProvider(writer, scope.ProvidedScaleFactors);
        WriteUpdateGroups(writer, groups);
        writer.Close();
    }

    private static List<PointPlan> CollectPoints(SunSpecGroupDefinition group, bool isTopLevel, OwnerScope scope, FileState state)
    {
        var ownPointNames = group.Points.Select(point => point.Name).ToHashSet(StringComparer.Ordinal);
        var points = new List<PointPlan>();
        foreach (var (point, pointOffset, map) in SunSpecPointMapping.GetPropertyPoints(group, isTopLevel))
        {
            var name = CSharpText.ToIdentifier(point.Name);
            AddMember(scope.Members, name, scope.Prefix);

            var scaleFactorProperty = GetScaleFactorProperty(name, map, ownPointNames, scope);
            points.Add(new PointPlan(
                name,
                GetTypeName(map, scope.Prefix, point, state),
                CSharpText.XmlText(point.Description ?? point.Label ?? point.Name),
                FormatRegisterAttribute(pointOffset, map, scaleFactorProperty),
                map.Kind == SunSpecValueKind.ScaleFactor ? null : FormatStateAttribute(map)));
        }

        return points;
    }

    // Returns the scale factor point of the same subject, or null when there is none or when it lives in an
    // enclosing group, which the owner then supplies through IModbusScaleFactorProvider.
    private static string? GetScaleFactorProperty(string name, SunSpecPointMap map, HashSet<string> ownPointNames, OwnerScope scope)
    {
        if (map.ScaleFactorPointName is not { } scaleFactorName)
        {
            return null;
        }

        if (ownPointNames.Contains(scaleFactorName))
        {
            return CSharpText.ToIdentifier(scaleFactorName);
        }

        scope.ProvidedScaleFactors.Add((name, ResolveAncestorScaleFactor(scaleFactorName, scope)));
        return null;
    }

    private static string FormatRegisterAttribute(int offset, SunSpecPointMap map, string? scaleFactorProperty)
    {
        var arguments = new List<string> { CSharpText.Integer(offset), $"ModbusDataType.{map.DataType}" };
        if (map.StringLength > 0)
        {
            arguments.Add($"Length = {CSharpText.Integer(map.StringLength)}");
        }

        if (map.Scale != 1m)
        {
            arguments.Add($"Scale = {CSharpText.NumberLiteral(map.Scale)}");
        }

        if (scaleFactorProperty is not null)
        {
            arguments.Add($"ScaleFactorProperty = nameof({scaleFactorProperty})");
        }

        if (map.NotAvailableValue != ModbusNotAvailableValue.None)
        {
            arguments.Add($"NotAvailableValue = ModbusNotAvailableValue.{map.NotAvailableValue}");
        }

        if (map.IsReadOnly)
        {
            arguments.Add("Access = ModbusAccess.ReadOnly");
        }

        return $"[ModbusRegister({string.Join(", ", arguments)})]";
    }

    private static List<GroupPropertyPlan> CollectGroups(
        SunSpecGroupDefinition group, string ownerClassName, OwnerScope scope,
        IReadOnlyList<AncestorInfo> childAncestors, FileState state, string modelsText)
    {
        var groups = new List<GroupPropertyPlan>();
        foreach (var child in group.Groups)
        {
            var propertyName = CSharpText.ToIdentifier(SunSpecNames.ToPascalCase(child.Name));
            AddMember(scope.Members, propertyName, scope.Prefix);

            var className = $"{scope.Prefix}{propertyName}Group";
            AddTypeName(state.TypeNames, className);

            groups.Add(new GroupPropertyPlan(propertyName, child.Name, className, child.Count.IsSingle, CSharpText.XmlText(child.Description ?? Label(child))));
            state.GroupClasses.Add(new GroupPlan(child, className, ownerClassName, childAncestors, modelsText));
        }

        return groups;
    }

    private static string ResolveAncestorScaleFactor(string scaleFactorName, OwnerScope scope)
    {
        for (var level = 0; level < scope.Ancestors.Count; level++)
        {
            var ancestor = scope.Ancestors[level];
            if (ancestor.Group.Points.Any(point => point.Name == scaleFactorName))
            {
                var path = string.Join(".", Enumerable.Repeat("Parent", level + 1));
                return $"new PropertyReference({path}, nameof({ancestor.ClassName}.{CSharpText.ToIdentifier(scaleFactorName)}))";
            }
        }

        throw new InvalidDataException($"Scale factor {scaleFactorName} used in {scope.Prefix} is not defined in an enclosing group.");
    }

    private static string GetTypeName(SunSpecPointMap map, string ownerPrefix, SunSpecPointDefinition point, FileState state)
    {
        switch (map.Kind)
        {
            case SunSpecValueKind.Number:
                return "decimal?";
            case SunSpecValueKind.Duration:
                return "TimeSpan?";
            case SunSpecValueKind.Text:
                return "string?";
            case SunSpecValueKind.Enumeration or SunSpecValueKind.Flags:
                var enumName = ownerPrefix + CSharpText.ToIdentifier(point.Name);
                AddTypeName(state.TypeNames, enumName);
                state.Enums.Add(new EnumPlan(enumName, point, map));
                return enumName + "?";
            default:
                return GetIntegerTypeName(map.RawType);
        }
    }

    private static string GetIntegerTypeName(Type rawType) => Type.GetTypeCode(rawType) switch
    {
        TypeCode.Int16 => "short?",
        TypeCode.UInt16 => "ushort?",
        TypeCode.Int32 => "int?",
        TypeCode.UInt32 => "uint?",
        TypeCode.Int64 => "long?",
        _ => "ulong?"
    };

    private static string FormatStateAttribute(SunSpecPointMap map)
    {
        var arguments = new List<string> { $"Title = {CSharpText.Literal(map.Title)}" };
        if (map.Unit != StateUnit.Default)
        {
            arguments.Add($"Unit = StateUnit.{map.Unit}");
        }

        if (map.IsCumulative)
        {
            arguments.Add("IsCumulative = true");
        }

        if (map.Kind is SunSpecValueKind.Enumeration or SunSpecValueKind.Flags)
        {
            arguments.Add("IsDiscrete = true");
        }

        return $"[State({string.Join(", ", arguments)})]";
    }

    private static void WriteInitializers(CodeWriter writer, List<PointPlan> points, List<GroupPropertyPlan> groups)
    {
        foreach (var point in points)
        {
            writer.Line($"{point.Name} = null;");
        }

        foreach (var group in groups)
        {
            writer.Line(group.IsSingle ? $"{group.PropertyName} = null;" : $"{group.PropertyName} = [];");
        }
    }

    private static void WritePoints(CodeWriter writer, List<PointPlan> points)
    {
        foreach (var point in points)
        {
            writer.Line();
            writer.Summary(point.Documentation);
            writer.Line(point.RegisterAttribute);
            if (point.StateAttribute is { } stateAttribute)
            {
                writer.Line(stateAttribute);
            }

            writer.Line($"public partial {point.TypeName} {point.Name} {{ get; internal set; }}");
        }
    }

    private static void WriteGroupProperties(CodeWriter writer, List<GroupPropertyPlan> groups)
    {
        foreach (var group in groups)
        {
            writer.Line();
            writer.Summary(group.Documentation);
            writer.Line(group.IsSingle
                ? $"public partial {group.ClassName}? {group.PropertyName} {{ get; internal set; }}"
                : $"public partial {group.ClassName}[] {group.PropertyName} {{ get; internal set; }}");
        }
    }

    private static void WriteScaleFactorProvider(CodeWriter writer, List<(string Name, string Expression)> providedScaleFactors)
    {
        if (providedScaleFactors.Count == 0)
        {
            return;
        }

        writer.Line();
        writer.Line("PropertyReference? IModbusScaleFactorProvider.TryGetScaleFactorProperty(string propertyName) => propertyName switch");
        writer.Open();
        foreach (var (name, expression) in providedScaleFactors)
        {
            writer.Line($"nameof({name}) => {expression},");
        }

        writer.Line("_ => null");
        writer.Close(";");
    }

    private static void WriteUpdateGroups(CodeWriter writer, List<GroupPropertyPlan> groups)
    {
        if (groups.Count == 0)
        {
            return;
        }

        writer.Line();
        writer.Line("void ISunSpecGroupOwner.UpdateGroups(SunSpecGroupInstance instance)");
        writer.Open();
        foreach (var group in groups)
        {
            var method = group.IsSingle ? "UpdateSingle" : "Update";
            writer.Line($"{group.PropertyName} = SunSpecGroups.{method}({group.PropertyName}, instance.GetGroup({CSharpText.Literal(group.GroupName)}), group => new {group.ClassName}(this, group.Address, group.Index));");
        }

        writer.Close();
    }

    private static void WriteEnum(CodeWriter writer, EnumPlan plan)
    {
        var isFlags = plan.Map.Kind == SunSpecValueKind.Flags;
        var is16Bit = plan.Map.DataType == ModbusDataType.U16;

        writer.Line();
        writer.Summary(CSharpText.XmlText(plan.Point.Description ?? plan.Point.Label ?? plan.Point.Name));
        if (isFlags)
        {
            writer.Line("[Flags]");
        }

        writer.Line($"public enum {plan.Name} : {(is16Bit ? "ushort" : "uint")}");
        writer.Open();
        var memberNames = new HashSet<string>(StringComparer.Ordinal);
        for (var index = 0; index < plan.Point.Symbols.Count; index++)
        {
            var symbol = plan.Point.Symbols[index];
            var name = GetEnumMemberName(plan.Name, symbol, memberNames);
            if (index > 0)
            {
                writer.Line();
            }

            if (GetSymbolDocumentation(symbol) is { } documentation)
            {
                writer.Summary(CSharpText.XmlText(documentation));
            }

            writer.Line($"{name} = {EnumValue(plan.Name, symbol, isFlags, is16Bit)},");
        }

        writer.Close();
    }

    // A member name used by an earlier symbol gets the symbol value appended.
    private static string GetEnumMemberName(string enumName, SunSpecSymbolDefinition symbol, HashSet<string> memberNames)
    {
        var name = CSharpText.ToEnumMemberName(symbol.Name);
        if (memberNames.Add(name))
        {
            return name;
        }

        var fallbackName = $"{name}_{CSharpText.Integer(symbol.Value)}";
        return memberNames.Add(fallbackName)
            ? fallbackName
            : throw new InvalidDataException($"Symbol {symbol.Name} of {enumName} collides as {name} and as {fallbackName} with other members.");
    }

    // Returns the label or else the description, or null when neither adds anything to the symbol name.
    private static string? GetSymbolDocumentation(SunSpecSymbolDefinition symbol)
    {
        if (IsDocumentation(symbol.Label, symbol.Name))
        {
            return symbol.Label;
        }

        return IsDocumentation(symbol.Description, symbol.Name) ? symbol.Description : null;
    }

    private static bool IsDocumentation([NotNullWhen(true)] string? text, string name)
        => !string.IsNullOrWhiteSpace(text) && text.Trim() != name;

    // A bit field symbol value is a bit number; an enumeration symbol value is the raw value.
    private static string EnumValue(string enumName, SunSpecSymbolDefinition symbol, bool isFlags, bool is16Bit)
    {
        var bitCount = is16Bit ? 16 : 32;
        var limit = isFlags ? bitCount : 1L << bitCount;
        if (symbol.Value < 0 || symbol.Value >= limit)
        {
            throw new InvalidDataException($"Symbol {symbol.Name} of {enumName} does not fit {(is16Bit ? "ushort" : "uint")}.");
        }

        return isFlags
            ? $"0x{(1UL << (int)symbol.Value).ToString("X", CultureInfo.InvariantCulture)}"
            : CSharpText.Integer(symbol.Value);
    }

    private static string Label(SunSpecGroupDefinition group)
        => string.IsNullOrWhiteSpace(group.Label) ? SunSpecNames.ToPascalCase(group.Name) : group.Label.Trim();

    private static string Description(SunSpecGroupDefinition group)
        => string.IsNullOrWhiteSpace(group.Description) ? string.Empty : " " + CSharpText.XmlText(group.Description);

    private static void AddTypeName(HashSet<string> typeNames, string name)
    {
        if (!typeNames.Add(name))
        {
            throw new InvalidDataException($"The generated type name {name} is not unique.");
        }
    }

    private static void AddMember(HashSet<string> members, string name, string ownerPrefix)
    {
        if (!members.Add(name))
        {
            throw new InvalidDataException($"The member {name} of {ownerPrefix} collides with another member.");
        }
    }
}
