<Project Sdk="Microsoft.NET.Sdk.Razor">

    <ItemGroup>
        <ProjectReference Include="..\HomeBlaze.History.Sqlite\HomeBlaze.History.Sqlite.csproj" />
        <ProjectReference Include="..\HomeBlaze.Components.Abstractions\HomeBlaze.Components.Abstractions.csproj" />
        <PackageReference Include="MudBlazor" />
    </ItemGroup>

</Project>
